name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    paths: [ ".github/workflows/docker-image.yml", "kaniq", "Dockerfile" ]
  pull_request:
    branches: [ "develop" ]
    paths: [ ".github/workflows/docker-image.yml", "kaniq", "Dockerfile" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "::set-output value=$(git describe --tags)"
      id: git_version

    - uses: docker/build-push-action@v3.0.0
      with:
        push: true
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/niklasrosenstein/kaniq:latest,ghcr.io/niklasrosenstein/kaniq:${{ steps.git_version.value }}
