name: Docker Image CI

on:
  push:
    branches: [ "develop" ]
    paths: [ ".github/workflows/docker-image.yml", "kaniq", "Dockerfile" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "develop" ]
    paths: [ ".github/workflows/docker-image.yml", "kaniq", "Dockerfile" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: docker/setup-qemu-action@v2
    - uses: docker/setup-buildx-action@v2
    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "::set-output name=value::$(git describe --tags)"
      id: git_version

    - name: Build and push (snapshot)
      uses: docker/build-push-action@v3.0.0
      if: "!(github.ref == 'refs/heads/develop') && !startsWith(github.ref, 'refs/tags/')"
      with:
        push: true
        build-args: GIT_VERSION=${{ steps.git_version.outputs.value }}
        cache-to: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        cache-from: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/niklasrosenstein/kaniq:${{ steps.git_version.outputs.value }}

    - name: Build and push (develop)
      uses: docker/build-push-action@v3.0.0
      if: github.ref == 'refs/heads/develop'
      with:
        push: true
        build-args: GIT_VERSION=${{ steps.git_version.outputs.value }}
        cache-to: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        cache-from: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/niklasrosenstein/kaniq:develop,ghcr.io/niklasrosenstein/kaniq:${{ steps.git_version.outputs.value }}

    - name: Build and push (latest)
      uses: docker/build-push-action@v3.0.0
      if: startsWith(github.ref, 'refs/tags/')
      with:
        push: true
        build-args: GIT_VERSION=${{ steps.git_version.outputs.value }}
        cache-to: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        cache-from: type=registry,ref=ghcr.io/niklasrosenstein/kaniq:_cache
        platforms: linux/amd64,linux/arm64
        tags: ghcr.io/niklasrosenstein/kaniq:latest,ghcr.io/niklasrosenstein/kaniq:${{ steps.git_version.outputs.value }}
