name: Rust

on:
  push:
    branches: [ "develop" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "develop" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build
      run: cd kaniq && cargo build --verbose --release

    - run: echo "::set-output name=value::$(git describe --tags)"
      id: git_version
    - run: echo "::set-output name=value::$(uname)-$(arch)"
      id: os

    # - name: Run tests
    #   run: cd kaniq && cargo test --verbose

    - uses: actions/upload-artifact@v3.1.0
      with:
        name: kaniq-${{ steps.os.outputs.value }}-${{ steps.git_version.outputs.value }}
        path: kaniq/target/release/kaniq

    - uses: svenstaro/upload-release-action@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: kaniq/target/release/kaniq
        asset_name: kaniq-${{ steps.os.outputs.value }}-${{ steps.git_version.outputs.value }}
        tag: ${{ github.ref }}
        overwrite: true
